### ISSUE TITLE
Failed payment by SEPA Direct Debit creates order

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#234]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/prestashop-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of PrestaShop](https://github.com/wirecard/prestashop-ee/wiki#download-prestashop-shop-module).

### Versions

**PrestaShop version:** 1.7.5.1
**PHP version:** 7.1

### Issue

If incorrect SEPA data is entered for a direct debit, an order will still be created. The customer receives the error message on the page of the first step of the checkout. He has to go through the checkout steps again until he can enter new payment data.

The fact that an order is created means that an order confirmation is sent to the customer even though the order was not successful and the customer is also not forwarded to the order confirmation. The customer thus receives an error message in the checkout process but an order confirmation by e-mail.

In spite of the wrong payment data, a payment by SEPA direct debit is displayed for the created order - but without transaction ID.

**Comment by tomazpu** [comment]
Hello @fuchsbart, 

First point: As already discussed in another thread, that's normal and expected behavior. After a submit the order is created, and if an error happens it will later be set to error order status.

The order confirmation email is just a notice that an order was accepted from the consumer, it doesn't mean that the payment or order in generall is successful. If the order is successful he will receive another email at a later stage.

And to the last point. Very good input, I will open an issue and we will set the transaction id for failed payments. Thank you!

Best regards,
Tomaz

**Comment by tomazpu** [comment]
Hi @fuchsbart, 

today we released a new plugin version where we now set the transaction id for failed orders.

Thank you for your input. I will close now the issue.
Best regards Tomaz
